### ISSUE TITLE
cannot build following instructions

### ISSUE THREAD

**Issue by ezeql** [papplampe/virgo#7]
$ mingw32-make.exe
cc -o virgo.o -O3 -nostdlib -fno-asynchronous-unwind-tables -fno-builtin -fno-ident -ffunction-sections -fdata-sections -Wall -m32 -c virgo.c
Makefile:25: recipe for target 'virgo.o' failed
process_begin: CreateProcess(NULL, cc -o virgo.o -O3 -nostdlib -fno-asynchronous-unwind-tables -fno-builtin -fno-ident -ffunction-sections -fdata-sections -Wall -m32 -c virgo.c, ...) failed.
make (e=2): The system cannot find the file specified.
mingw32-make: *** [virgo.o] Error 2

**Comment by ezeql** [comment]
I know this has something to do with mingw  side, any help will be appreciated.

**Comment by papplampe** [comment]
cc is probably not defined. Set the environment variable for CC to gcc or whatever compiler you are using. Either in the Makefile, cmd or permanently in the environment variables.

**Comment by ezeql** [comment]
Thanks. Also why  mingw-w64-i686-gcc  instead of x86_64 ?

**Comment by papplampe** [comment]
Laziness. A 32bit executable works on both 32bit and 64bit machines.

**Comment by ezeql** [comment]
:ok_hand:
